### ISSUE TITLE
Feature Request: TheDraw Font (.TDF) file support

### ISSUE THREAD

**Issue by kalleswe** [blocktronics/moebius#197] opened 2021-08-12 11:19 UTC
Request for a TDF file and to make a font library so you can easily write using TheDraw font files.
For example: http://www.roysac.com/thedrawfonts-tdf.html

**Comment by bart-d** [comment] 2021-08-14 04:57
Duplicate of https://github.com/blocktronics/moebius/issues/34

**Closed by bart-d** 2021-08-14 04:57 UTC
