### ISSUE TITLE
Recent Documents menu no longer working on Mac

### ISSUE THREAD

**Issue by andyherbert** [blocktronics/moebius#81] opened 2019-08-18 09:33 UTC

**Comment by andyherbert** [comment] 2019-08-21 15:21
Appears to be broken in electron, awaiting fix.

**Comment by bart-d** [comment] 2020-04-29 21:57
<img width="295" alt="Screenshot 2020-04-29 at 23 54 51" src="https://user-images.githubusercontent.com/6034441/80650860-110b9580-8a75-11ea-8713-872e15f920fb.png">

I'm not able to reproduce this, anyone?

**Comment by andyherbert** [comment] 2020-04-30 11:50
The problem is with recent documents not showing in the application menus, not the dock icon.

There was a (couple of) issues raised on the electron repo, the latest being this one:

https://github.com/electron/electron/issues/20503

Apparently to that thread it was fixed with 7.0.1 (this repo uses 6.0.8) and bumping it to that version does fix the issue, but the Electron API is a bit of a moving target and I'm not sure if anything got deprecated by 6 and 7, a quick cursory glance at the notes suggests not, but it's a possibility to keep in mind.

**Comment by bart-d** [comment] 2020-04-30 18:46
<img width="498" alt="Screenshot 2020-04-30 at 20 44 32" src="https://user-images.githubusercontent.com/6034441/80747328-9188cf80-8b23-11ea-9985-b1a1d8aae3fc.png">

it does seem fixed in Electron 7 indeed, so far no other issues seen

**Closed** 2020-05-01 07:59 UTC
